### ISSUE TITLE
Peninsular (West) Malaysia MY-WM data not working 

### ISSUE THREAD

**Issue by mshuflin** [electricitymap/electricitymap-contrib#3278]
West Malaysia has no data. Errors say, "No exchange data is currently available for West Malaysia."  and "No production data is currently available for West Malaysia."

**Comment by mshuflin** [comment]
fuel_mix_url = 'https://www.gso.org.my/SystemData/FuelMix.aspx'
current_gen_url = 'https://www.gso.org.my/SystemData/CurrentGen.aspx'
exchanges_url = 'https://www.gso.org.my/SystemData/TieLine.aspx'

These three pages are functional

**Comment by jarek** [comment]
From a very quick glance, looks like their HTML might have changed?

logs have:

```
Traceback (most recent call last):
  File "/home/src/electricitymap/contrib/parsers/MY_WM.py", line 48, in get_data
    ts_tag = gen_mw.findNext('td')
AttributeError: 'NoneType' object has no attribute 'findNext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projects/feeder-electricity/src/lib/fetch_data.py", line 206, in launch_parsers
    objs = res.get(timeout) or []
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/projects/feeder-electricity/src/lib/fetch_data.py", line 202, in <lambda>
    *keys, session, logger=public_logger, **parser_kwargs
  File "/home/src/electricitymap/contrib/parsers/MY_WM.py", line 120, in fetch_production
    raw_data = get_data(session=None)
  File "/home/src/electricitymap/contrib/parsers/MY_WM.py", line 54, in get_data
    raise ValueError('No production data is currently available for West Malaysia.')
ValueError: No production data is currently available for West Malaysia.
```

**Comment by mshuflin** [comment]
Is there a way I can help resolve this?

**Comment by Manu1400** [comment]
in `fetch_production` method, prefer fetch XML live data : 
POST https://www.gso.org.my/SystemData/CurrentGen.aspx/DownloadFile with payload :
`{"Fromdate":"15/08/2021","Todate":"15/08/2021"}`

### XML
part of XML :
```xml
<?xml version="1.0" standalone="yes"?><DocumentElement>
  <DataTable>
    <DT>2021-08-15T22:00:00+08:00</DT>
    <MW>13657</MW>
  </DataTable>
  <DataTable>
    <DT>2021-08-15T21:50:00+08:00</DT>
    <MW>13748</MW>
```

### curl
```bash
curl 'https://www.gso.org.my/SystemData/CurrentGen.aspx/DownloadFile' \
  -H 'content-type: application/json' \
  --data-raw '{"Fromdate":"15/08/2021","Todate":"15/08/2021"}'
```

Notes:
* header `content-type: application/json` is mandatory
* but return XML 🤕

**Comment by jarek** [comment]
Interesting, thanks for pointing this out! I wonder if the page has been amended to use XML/JSON services since we implemented the parser?

Observing the network requests that https://www.gso.org.my/SystemData/FuelMix.aspx is making, I see a POST request to https://www.gso.org.my/SystemData/FuelMix.aspx/GetChartDataSource that returns JSON:

`curl 'https://www.gso.org.my/SystemData/FuelMix.aspx/GetChartDataSource' -H 'Content-Type: application/json; charset=utf-8' --data-raw '{"dtFrom":"15/08/2021","dtTo":"15/08/2021"}'`

response

`{"d":"[{\"Descp\":\"ST-Gas            \",\"SumMW\":0},{\"Descp\":\"ST-Coal           \",\"SumMW\":7830},{\"Descp\":\"OCGT-Gas          \",\"SumMW\":0},{\"Descp\":\"LSS               \",\"SumMW\":0},{\"Descp\":\"Hydro             \",\"SumMW\":566},{\"Descp\":\"Co-Gen            \",\"SumMW\":9},{\"Descp\":\"CCGT-Gas          \",\"SumMW\":5742}]"}`

That's JSON embedded in JSON :dizzy_face: but that's doable and might be easier than XML

**Comment by mshuflin** [comment]
Anything I can do to help get this fixed?

**Comment by gwpicard** [comment]
Is this still breaking?

**Comment by kruschk** [comment]
Yes, it's still broken. I'm wondering if it's really necessary to use the fuel mix at all. The https://www.gso.org.my/SystemData/CurrentGen.aspx/GetChartDataSource POST endpoint provides a slightly higher-level breakdown that seems better-suited to our purposes and appears to be based on the same data. It also behaves more consistently between fetching current and historical data: it provides a list of generation breakdowns from the beginning of the day until the current time or the end of the day. Compare the following:

**Fuel mix:**

```bash
curl --header 'Content-Type: application/json' --data-raw '{"dtFrom": "17/04/2022", "dtTo": "17/04/2022"}' 'https://www.gso.org.my/SystemData/FuelMix.aspx/GetChartDataSource'
```

```
[{'Descp': 'ST-Gas            ', 'SumMW': 0},
 {'Descp': 'ST-Coal           ', 'SumMW': 9142},
 {'Descp': 'OCGT-Gas          ', 'SumMW': 0},
 {'Descp': 'LSS               ', 'SumMW': 3},
 {'Descp': 'Hydro             ', 'SumMW': 226},
 {'Descp': 'Co-Gen            ', 'SumMW': 50},
 {'Descp': 'CCGT-Gas          ', 'SumMW': 3539}]
```

**Current generation:**

```bash
curl --header 'Content-Type: application/json' --data-raw '{"Fromdate": "17/04/2022", "Todate": "17/04/2022"}' 'https://www.gso.org.my/SystemData/CurrentGen.aspx/GetChartDataSource'
```

```
{'CoGen': 50,
 'Coal': 9142,
 'DT': '2022-04-18T04:50:00',
 'Gas': 3539,
 'Hydro': 226,
 'Oil': 0,
 'Solar': 3}
```

Using only the current generation would make it trivial to implement both current and historical data retrieval in `fetch_production`. Is there any benefit in keeping the fuel mix, or can we scrap it?

---

On a related note, we should now also be able to fetch JSON-formatted exchange data with a POST request:

```bash
curl --header 'Content-Type: application/json' --data-raw '{"Fromdate": "17/04/2022", "Todate": "17/04/2022", "Line": "EGAT"}' 'https://www.gso.org.my/SystemData/TieLine.aspx/GetChartDataSource'
```

No more fumbling around with ASP hacks!

**Comment by jarek** [comment]
I think I recall when the parser was first being implemented, the CurrentGen page only showed the total current generation value (as it still does in the table to the right of the chart). If it's got more detail now, we can use it, especially if it can give JSON more easily :+1:

**Comment by gwpicard** [comment]
I agree with @jarek — whatever granularity of data we can get, the better. Especially because as we develop more estimation models, it should become easier to "fill in the gaps". It would be great if you could take a crack at implementing this fix to the parser @kruschk !

**Comment by q--** [comment]
Not sure if anyone's noticed this yet, but the [homepage](https://www.gso.org.my/LandingPage.aspx) now features a near real-time generation profile for the current day, including fuel mix. It has data up to less than half an hour ago.

**Comment by madsnedergaard** [comment]
Should be back up thanks to @kruschk, will keep the issue open until data flows again :)

**Comment by madsnedergaard** [comment]
Data looks good on the map: https://app.electricitymap.org/zone/MY-WM

Closing this again 🎉
